### ISSUE TITLE
[bug] There is little content per line in this theme when scaled to side

### ISSUE THREAD

**Issue by imingx** [george-paul/typoratheme-paradox#1]
Thanks for your beautiful theme.

But when I place the typora window on the left side of the screen, there is very little content per line:

<img width="923" alt="image" src="https://user-images.githubusercontent.com/54981719/168580479-5cecba0e-ea79-4fd3-92c7-9d3484d180e3.png">

other themes:

<img width="923" alt="image" src="https://user-images.githubusercontent.com/54981719/168581181-0e8cb920-ccf6-4c24-83cd-534928662109.png">

**Comment by XIUXIUXIUBIUA** [comment]
You can modify the item _--main-content-max-width_ in _paradox-seraph.css_ to change the width presented in the editor.

**Comment by george-paul** [comment]
@imingx This is actually entirely on purpose, I tuned it to be the width it would be when printed on A4. The thing is, I don't normally edit with the sidebar open so admittedly it does look awkward with the sidebar open (and possibly on what looks like a lower-width screen).

The fix that @XIUXIUXIUBIUA proposed should work for anyone looking to write with the sidebar open.
